---
title: "Cece-sharks"
output: html_document
---
## Project Concept

In this project, I will be exploring data outlining shark attacks in Australia from 1791 until the present day. I want to know if there is a correlation between fatal and provoked attacks, and what types of sharks are most likely to participate in provoked vs unprovoked attacks. 

```{r, echo=FALSE}
#Loading in packages and csv files
library(dplyr)
library(ggplot2)
top_sharks <- read.csv("../data/top.sharks.csv")
filtered_data_sharks <- select(top_sharks, Recovery.status, Provoked.unprovoked)
fatality_data <- filter(filtered_data_sharks, Recovery.status == "fatal", Provoked.unprovoked == c("Provoked", "Unprovoked"))
```



## Data: Is there a correlation between provoked and fatal attacks? 
```{r, echo=FALSE}
ggplot(data = fatality_data, mapping = aes(x = Provoked.unprovoked, y = Recovery.status)) +
  geom_bar(stat="identity", color="blue") +
  labs(x= "Provoked or Unprovoked Attack", y= "Human Recovery Status: Fatal")
```

